[package]
name = "strata-asm-stf"
version = "0.1.0"
edition = "2024"

[lints]
rust.missing_debug_implementations = "warn"
rust.rust_2018_idioms = { level = "deny", priority = -1 }
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "deny"
rust.unused_must_use = "deny"
rust.missing_docs = "warn"
rustdoc.all = "warn"

[dependencies]
bitcoin.workspace = true
strata-asm-common.workspace = true
strata-asm-proto-bridge-v1.workspace = true
strata-asm-proto-core.workspace = true
