use strata_proofimpl_cl_stf::process_cl_stf;
use strata_risc0_adapter::ZkVmRisc0;

// TODO: replace this with vks file that'll generated by build.rs script similar to how things are
// implemented for sp1-guest-builder
pub const GUEST_EVM_EE_STF_ELF_ID: &[u32; 8] = &[0, 0, 0, 0, 0, 0, 0, 0];

fn main() {
    process_cl_stf(&ZkVmRisc0, GUEST_EVM_EE_STF_ELF_ID);
}
