use strata_eectl::errors::EngineError;
use strata_primitives::prelude::*;
use thiserror::Error;

/// Return type for worker messages.
pub type WorkerResult<T> = Result<T, WorkerError>;

#[derive(Debug, Error)]
pub enum WorkerError {
    #[error("missing block {0}")]
    MissingL2Block(L2BlockId),

    /// This usually means that we didn't execute the previous block.
    #[error("missing pre-state to execute block {0:?}")]
    MissingPreState(L2BlockCommitment),

    /// This might point to a database corruption or misused admin commands.
    /// The worker should not have tried to access block outputs that are
    /// missing.
    #[error("missing exec output for block {0:?}")]
    MissingBlockOutput(L2BlockCommitment),

    /// This means that we haven't executed the block that's the terminal for an epoch.
    #[error("missing inner post-state of epoch {0} terminal {1:?}")]
    MissingEpochInnerPostState(u64, L2BlockCommitment),

    /// Generated by the worker handle when the worker has exited before being
    /// able to process a message we were trying to send.
    #[error("chain worker exited")]
    WorkerExited,

    #[error("OL block execution: {0}")]
    Exec(#[from] strata_chainexec::Error),

    #[error("engine: {0}")]
    Engine(#[from] EngineError),

    #[error("not yet implemented")]
    Unimplemented,
}

/// Weird impl that we need to go "back down" for context fns.
// TODO maybe restructure error types so we don't need this?
impl Into<strata_chainexec::Error> for WorkerError {
    fn into(self) -> strata_chainexec::Error {
        use strata_chainexec::Error as ExecError;
        match self {
            WorkerError::MissingL2Block(block) => ExecError::MissingL2Header(block),
            WorkerError::MissingPreState(block) => ExecError::MissingBlockPreState(*block.blkid()),
            WorkerError::MissingBlockOutput(block) => {
                ExecError::MissingBlockPostState(*block.blkid())
            }
            WorkerError::MissingEpochInnerPostState(_, block) => {
                ExecError::MissingBlockPostState(*block.blkid())
            }
            WorkerError::Exec(e) => e, // passthrough self
            WorkerError::WorkerExited | WorkerError::Engine(_) => {
                ExecError::Unexpected("exec worker error".to_owned())
            }
            WorkerError::Unimplemented => ExecError::Unimplemented,
        }
    }
}
