[client]
rpc_port = 8432
l2_blocks_fetch_limit = 1_000
datadir = "./.data"
sequencer_key = "./test_seqkey.bin"
# sequencer_bitcoin_address = ""
sequencer_bitcoin_address = "bcrt1qyk7jrmlehs6dt2xfmkxp9a0rxe7xn4fqxxc29e"
db_retry_count = 5

[bitcoind_rpc]
# rpc_url = "localhost:18445"
rpc_url = "localhost:8333"
rpc_user = "rpcuser"
rpc_password = "rpcpassword"
network = "regtest"

[sync]
l1_follow_distance = 6
max_reorg_depth = 4
client_poll_dur_ms = 200
client_checkpoint_interval = 10

[exec.reth]
# reth {authrpc.address}:{authrpc.port}
rpc_url = "localhost:8551"
# reth authrpc.jwtsecret path
secret = "./.data/reth/jwt.hex"
