[package]
edition = "2021"
name = "strata-dbtool"
version = "0.1.0"

[[bin]]
name = "strata-dbtool"
path = "src/main.rs"

[dependencies]
rockbound.workspace = true
strata-rocksdb.workspace = true

anyhow.workspace = true
argh.workspace = true
bincode.workspace = true
borsh.workspace = true
hex.workspace = true
serde.workspace = true
