use strata_proofimpl_l1_batch::process_l1_batch_proof;
use strata_risc0_adapter::Risc0ZkVmEnv;

// TODO: replace this with vks file that'll generated by build.rs script similar to how things are
// implemented for sp1-guest-builder
pub const GUEST_BTC_BLOCKSPACE_ELF_ID: &[u32; 8] = &[0, 0, 0, 0, 0, 0, 0, 0];

fn main() {
    process_l1_batch_proof(&Risc0ZkVmEnv, GUEST_BTC_BLOCKSPACE_ELF_ID);
}
