[package]
edition = "2021"
name = "guest-risc0-checkpoint"
version = "0.1.0"

[workspace]

[dependencies]
strata-proofimpl-checkpoint = { path = "../../../crates/proof-impl/checkpoint" }
strata-risc0-adapter = { path = "../../../crates/zkvm/adapters/risc0" }

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
