[package]
edition = "2021"
name = "guest-risc0-checkpoint"
version = "0.1.0"

[workspace]

[dependencies]
bitcoin = "0.32.1"
borsh = { version = "1.5.0", features = ["derive"] }
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
sha2 = "0.10.8"
strata-primitives = { path = "../../../crates/primitives" }
strata-proofimpl-btc-blockspace = { path = "../../../crates/proof-impl/btc-blockspace" }
strata-proofimpl-checkpoint = { path = "../../../crates/proof-impl/checkpoint" }
strata-proofimpl-l1-batch = { path = "../../../crates/proof-impl/l1-batch" }
strata-state = { path = "../../../crates/state" }
strata-zkvm = { path = "../../../crates/zkvm/zkvm" }

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
