[package]
edition = "2021"
name = "strata-risc0-guest-builder"
version = "0.1.0"

[dependencies]
risc0-zkvm = "1.2.5"
zkaleido-risc0-host = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc7" }

[dev-dependencies]
bincode.workspace = true
bitcoin.workspace = true
borsh.workspace = true
hex.workspace = true
rand.workspace = true
strata-chaintsn.workspace = true
strata-primitives.workspace = true
strata-proofimpl-btc-blockspace.workspace = true
strata-proofimpl-checkpoint.workspace = true
strata-proofimpl-cl-stf.workspace = true
strata-proofimpl-evm-ee-stf.workspace = true
strata-state.workspace = true
strata-test-utils.workspace = true
zkaleido.workspace = true

[build-dependencies]
risc0-build = "1.1.2"

[package.metadata.risc0]
methods = [
  "guest-evm-ee-stf",
  "guest-cl-stf",
  "guest-cl-agg",
  "guest-btc-blockspace",
  "guest-l1-batch",
  "guest-checkpoint",
]
