services:
  reth:
    build:
      context: ../
      dockerfile: ./docker/alpen-reth/Dockerfile
    platform: linux/amd64
    image: public.ecr.aws/r1l9t0r6/tn1/alpen-reth:latest
    environment:
      BUILD_PROFILE: ${BUILD_PROFILE:-release}
      RETH_AUTH_RPC_PORT: ${RETH_AUTH_RPC_PORT:-8551}
      JWTSECRET: ${JWTSECRET:-configs/jwt.hex}
    volumes:
      - ./data/reth:/app/reth
      - ./configs:/app/configs
    ports:
      - "${RETH_AUTH_RPC_PORT:-8551}:${RETH_AUTH_RPC_PORT:-8551}"
      - "${RETH_PORT:-8545}:${RETH_PORT:-8545}"
    expose:
      - ${RETH_AUTH_RPC_PORT:-8551}
      - ${RETH_PORT:-8545}
    networks:
      - strata_network

  client:
    build:
      context: ../
      dockerfile: ./docker/strata-client/Dockerfile
    platform: linux/amd64
    image: public.ecr.aws/r1l9t0r6/testnet1/strata-client:latest
    environment:
      CONFIG_PATH: /app/configs/config.fn.toml
      PARAM_PATH: /app/configs/params.json
      RUST_LOG: ${RUST_LOG:-info}
    container_name: strata_client
    ports:
      - "8432:8432"
    volumes:
      - ./data/data-strata:/app/data
      - ./configs:/app/configs
    depends_on:
      - bitcoind
      - reth
    networks:
      - strata_network

  bitcoind:
    image: public.ecr.aws/s6b4k6i9/strata/signet:latest
    environment:
      MINERENABLED: 0
      ADDNODE: ${ADDNODE}
      SIGNETCHALLENGE: ${SIGNETCHALLENGE}
    container_name: strata_bitcoind
    volumes:
      - ./data/data-bitcoind:/root/.bitcoin/
    ports:
      - "38332:38332"
    expose:
      - ${BITCOIND_RPC_PORT:-9823}
    networks:
      - strata_network

networks:
  strata_network:
    driver: bridge
    name: strata_network
