[package]
name = "strata-chainexec"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-chaintsn.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true

anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
