use std::fmt::Display;

use serde::{de::DeserializeOwned, Serialize};

use crate::{
    input::ZkVmInputBuilder, ProofReceipt, ProofType, PublicValues, VerificationKey, ZkVmResult,
};

/// A trait implemented by the prover ("host") of a zkVM program.
pub trait ZkVmHost: Send + Sync + Clone + Display + 'static {
    type Input<'a>: ZkVmInputBuilder<'a>;

    /// Executes the guest code within the VM, generating and returning the validity proof.
    fn prove<'a>(
        &self,
        input: <Self::Input<'a> as ZkVmInputBuilder<'a>>::Input,
        proof_type: ProofType,
    ) -> ZkVmResult<ProofReceipt>;

    /// Reuturns the Verification key for the loaded ELF program
    fn get_verification_key(&self) -> VerificationKey;

    /// Extracts the public output from the public values using ZkVm's `serde`
    /// serialization/deserialization.
    fn extract_serde_public_output<T: Serialize + DeserializeOwned>(
        proof: &PublicValues,
    ) -> ZkVmResult<T>;

    /// Verifies the proof generated by the prover against the `program_id`.
    fn verify(&self, proof: &ProofReceipt) -> ZkVmResult<()>;
}
