use serde::{de::DeserializeOwned, Serialize};

/// Validity proof generated by the `ZKVMHost`
#[derive(Debug, Clone)]
pub struct Proof(Vec<u8>);

impl Proof {
    pub fn new(data: Vec<u8>) -> Self {
        Self(data)
    }

    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// Verification Key required to verify proof generated from `ZKVMHost`
#[derive(Debug, Clone)]
pub struct VerificationKey(pub Vec<u8>);

impl VerificationKey {
    pub fn new(data: Vec<u8>) -> Self {
        Self(data)
    }

    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// Prover config of the ZKVM Host
#[derive(Debug, Clone, Copy)]
pub struct ProverOptions {
    pub enable_compression: bool,
    pub use_mock_prover: bool,
    pub stark_to_snark_conversion: bool,
}

#[derive(Debug, Clone)]
pub struct ProverInput<T> {
    /// A collection of serde-serializable items. These will be automatically
    /// serialized and deserialized by the zkVM, providing a straightforward way
    /// to work with commonly supported data types.
    pub inputs: Vec<T>,
    /// A collection of pre-serialized byte arrays. Use this field when
    /// working with custom serializers/deserializers not natively supported by the zkVM, or when
    /// a custom approach offers performance advantages.
    pub serialized_inputs: Vec<Vec<u8>>,
    /// A set of inputs used specifically for the aggregation/composition program
    pub agg_inputs: Vec<AggregationInput>,
}

impl<T: serde::Serialize> ProverInput<T> {
    pub fn new() -> Self {
        ProverInput {
            inputs: vec![],
            serialized_inputs: vec![],
            agg_inputs: vec![],
        }
    }

    pub fn write(&mut self, value: T) {
        self.inputs.push(value);
    }

    pub fn write_serialized(&mut self, value: Vec<u8>) {
        self.serialized_inputs.push(value);
    }

    pub fn write_proof(&mut self, value: AggregationInput) {
        self.agg_inputs.push(value);
    }
}

impl<T: serde::Serialize> Default for ProverInput<T> {
    fn default() -> Self {
        Self::new()
    }
}

/// A trait implemented by the prover ("host") of a zkVM program.
pub trait ZKVMHost: Send + Sync + Clone {
    /// Initializes the ZKVM with the provided ELF program and prover configuration.
    fn init(guest_code: Vec<u8>, prover_options: ProverOptions) -> Self;

    /// Executes the guest code within the VM, generating and returning the validity proof.
    // TODO: Consider using custom error types instead of a generic error to capture the different
    // reasons proving can fail.
    fn prove<T: serde::Serialize>(
        &self,
        input: &ProverInput<T>,
    ) -> anyhow::Result<(Proof, VerificationKey)>;
}

/// A trait implemented by a verifier to decode and verify the proof generated by the prover
/// ("host").
pub trait ZKVMVerifier {
    /// Verifies the proof generated by the prover against the `program_id`.
    fn verify(verification_key: &VerificationKey, proof: &Proof) -> anyhow::Result<()>;

    /// Verifies the proof generated by the prover against the given `program_id` and
    /// `public_params`.
    fn verify_with_public_params<T: Serialize + DeserializeOwned>(
        verification_key: &VerificationKey,
        public_params: T,
        proof: &Proof,
    ) -> anyhow::Result<()>;

    /// Extracts the public output from the proof.
    fn extract_public_output<T: Serialize + DeserializeOwned>(proof: &Proof) -> anyhow::Result<T>;
}

impl Default for ProverOptions {
    fn default() -> Self {
        Self {
            enable_compression: false,
            use_mock_prover: true,
            stark_to_snark_conversion: false,
        }
    }
}

/// An input to the aggregation program.
///
/// Consists of a proof and a verification key.
#[derive(Debug, Clone)]
pub struct AggregationInput {
    proof: Proof,
    vk: VerificationKey,
}

impl AggregationInput {
    pub fn new(proof: Proof, vk: VerificationKey) -> Self {
        Self { proof, vk }
    }

    pub fn proof(&self) -> &Proof {
        &self.proof
    }

    pub fn vk(&self) -> &VerificationKey {
        &self.vk
    }
}
