use ::serde::Serialize;
use express_proofimpl_checkpoint::{
    self, process_checkpoint_proof, Groth16Proof, HashedCheckpointState, L2BatchProofOutput,
};
use express_proofimpl_l1_batch::logic::L1BatchProofOutput;
use risc0_zkvm::{
    guest::env,
    serde::{self, to_vec},
    Groth16Receipt, MaybePruned, ReceiptClaim,
};
use sha2::Digest;

fn main() {
    // TODO: update this
    let l1_batch: L1BatchProofOutput = env::read();

    let len: u32 = env::read();
    let mut slice = vec![0u8; len as usize];
    env::read_slice(&mut slice);
    let l2_batch: L2BatchProofOutput = borsh::from_slice(&slice).unwrap();

    // TODO: hardcode genesis
    let len: u32 = env::read();
    let mut slice = vec![0u8; len as usize];
    env::read_slice(&mut slice);
    let genesis: HashedCheckpointState = borsh::from_slice(&slice).unwrap();

    // Note: This code is just here to verify the validation of groth16 proof
    // TODO: remove this once we can test groth16 proof of the checkpoint proof itself
    let len: u32 = env::read();
    let mut l1_batch_groth16_proof = vec![0u8; len as usize];
    env::read_slice(&mut l1_batch_groth16_proof);

    // verify l1 proof
    // TODO: l1_batch_vk needs to be hardcoded
    let l1_batch_vk: [u32; 8] = env::read();
    env::verify(l1_batch_vk, &serde::to_vec(&l1_batch).unwrap()).unwrap();

    // verify l2 proof
    // TODO: implement this once CL batch is merged
    // let l2_batch_vk: [u32; 8] = env::read();
    // env::verify(l2_batch_vk, &serde::to_vec(&input.l2_state).unwrap()).unwrap();

    let (output, prev_checkpoint) = process_checkpoint_proof(&l1_batch, &l2_batch, &genesis);
    if let Some(prev_checkpoint) = prev_checkpoint {
        let checkpoint_vk: [u32; 8] = env::read();
        verify_groth16_proof(&prev_checkpoint.0, &prev_checkpoint.1, checkpoint_vk);
    }

    env::write(&output);
}

/// Verifies a Groth16 proof generated by the Risc0 VM.
///
/// This function takes the output generated by guest code running inside a Risc0 VM,
/// a raw Groth16 proof, and a verification key (vk). It computes the necessary
/// inputs for proof verification and asserts the integrity of the Groth16 proof.
///
/// # Parameters
/// - `output`: A reference to the output data generated by the guest code, which must implement the
///   `Serialize` trait. This output is expected to have been written using `env::write(&output)` in
///   the guest environment.
/// - `proof`: A reference to the raw Groth16 proof, which includes the proof elements `A`, `B`, and
///   `C` required for verification.
/// - `vk`: An array of 8 `u32` values representing the verification key (vk). This key is used to
///   verify the Groth16 proof and corresponds to the image ID of the proof being verified.
///
/// # Details
/// The function serializes the `output`, computes its SHA-256 hash, and converts the
/// hash into the format required by the Risc0 proof verification system. It then constructs
/// a `Groth16Receipt`, which includes the proof, claim, and input digest, and verifies
/// the integrity of the proof.
///
/// # Panics
/// The function will panic if the integrity check fails, meaning the Groth16 proof
/// verification did not pass.

fn verify_groth16_proof<T: Serialize>(guest_output: &T, proof: &Groth16Proof, vk: [u32; 8]) {
    let buf1: Vec<u8> = to_vec(&guest_output)
        .unwrap()
        .clone()
        .into_iter()
        .flat_map(|x| x.to_le_bytes().to_vec()) // Convert each u32 to 4 u8 bytes
        .collect();
    let input_hash: [u8; 32] = sha2::Sha256::digest(&buf1).into();
    let input_digest = risc0_zkvm::sha::Digest::from_bytes(input_hash);

    let claim = ReceiptClaim::ok(risc0_zkvm::sha::Digest::new(vk), MaybePruned::from(buf1));
    let claim = MaybePruned::from(claim);

    let receipt = Groth16Receipt::new(
        proof.clone(), // Actual Groth16 Proof(A, B, C)
        claim,         // Includes both digest and elf
        input_digest,  // This is not actually used underneath
    );

    let res = receipt.verify_integrity();
    assert!(res.is_ok())
}
