[package]
name = "strata-chain-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-chainexec.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true

anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
