[package]
name = "strata-native-zkvm-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
borsh.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sp1-sdk = { version = "3.0.0", optional = true }
strata-zkvm.workspace = true
tracing = { workspace = true }
